### ISSUE TITLE
[v7.0.1] layerBorderColorの設定項目のバグ

### ISSUE THREAD

**Issue by nea-c** [hebiiro/AviUtl-Plugin-OptimizeEditBox#2]
## 1. `RightColor`をオンにすると`BottomColor`が黒く描画される
→ `RightColor`をオンにして`BottomColor`を無効にすると確認できる。

## 2. LeftColorをオンにしてもLeft側の色が変わらない

**Comment by hebiiro** [comment]
version 7.1.0 で対応できたと思います。

**Comment by nea-c** [comment]
ありがとうございます
